name: Bump Homebrew nef formula

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  homebrew:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.TOKEN }}
        formula: git-extras
